- memcr.c
- memcr.h
- parasite.c
Introduced new variable - socket_dir and new, optional parameter to memcr: --parasite-socket-dir.
In case of parameter --parasite-socket-dir is specified, a socket is created under the given directory. Socket file has to be removed after restore to make checkpoint/restore available again. Sockets' names creation is unified in dedicated functions to concatenate strings once in the source code for each case. Existing 'dir' variables renamed to avoid confusion.
> Support both abstract sockets and sockets based on filesystem paths.

- memcr.c
This is of a typo category. Certain debug messages were disabled right before PoC was finished. Somehow this bug didn't cause any problems in testing.
> Fix target code and stack saving

- Makefile
- arch/arm/cpu.c
- arch/arm/enter.c
- arch/arm/parasite-head.S
This fixes compilation for Raspberry Pi Zero W target where movw and movt are not supported.
Assembler messages:
Error: selected processor does not support `movw r0,#0x2f00' in ARM mode
Error: selected processor does not support `movt r0,#0x8005' in ARM mode
Add -ffreestanding so that gcc doesn't insert a call to memcpy/memset in parasite code.
> arm: make asm code more generic + other fixes

- memcr.c
PTRACE_GETREGS and PTRACE_SETREGS are not supported on arm64.
> Use PTRACE_GETREGSET and PTRACE_SETREGSET to access registers

- memcr.c
Functions cmd_sequencer() and execute_parasite() are split to introduce new functionalities easier in the future.
> Split cmd_sequencer() and execute_parasite() functions.

- memcr-client.c
- memcr.c
- memcr.h
Service response introduced with OK or ERROR statuses. It is sent to client after checkpoint and after restore phase separately. Memcr can still handle only one PID at a time and expects strict parameters.
> Checkpont / restore procedures are synchronous now.

- arch/arm/enter.c
- arch/arm64/enter.c
- arch/x86_64/enter.c
- memcr.c
- memcr.h
Kernel sigset_t size is 8 bytes so the code now correctly handles peek/poke operation on 32 and 64 bit architectures. Also sigprocmask_blob is simplified as rt_sigprocmask syscall allows nset and oset point to the same address.
> Fix sigset handling

- memcr.c
Do not use incorrecd fd in case of accept() error.
> Abort procedure in case of restore socket failure.

- memcr.c
When memcr runs as a systemd service stdout is block buffered and logs are shown with a delay. To mitigate that make stdout line buffered as it is done when stdout refers to a terminal.
> Make stdout line buffered

- memcr.c
- parasite.c
xread() and xwrite() are intended for communication with parasite only so rename them to make it clear. For other purposes _read() and _write() wrappers are provided. Also don't wait for CMD_END response as the parasite could already exit by the time when memcr calls xread() CMD_END. memcr waits for parasite finish in parasite_status_wait().
> xread() and xwrite() cleanup

- memcr.c
- memcr.h
- parasite.c
With -f or --rss-file memcr will attempt to reduce file mapped read only memory regions as well. Pages from these regions are not saved to a page dump file as the memory content will be repopulated from the underlying mapped file on access.
Also minor fixes to parasite code are included.
> Implement handling of file mapped regions

- memcr.c
- memcr.h
With -m or --proc-mem memcr will download target pages from /proc/pid/mem interface. This should improve download times as there is less communication with the parasite. Also vm mapped pages are now read as continuous regions where possible (up to 1MB at once). This improves transfer speeds.
> Get memory pages from /proc/pid/mem interface

- memcr.c
- memcr.h
- parasite.c
We know parasite pid from clone() syscall so no need to read it from parasite.
> Drop CMD_GET_TID

- memcr.c
- memcr.h
- parasite.c
Parasite code, args and stack reside in a single region previously allocated with mmap() and there are no allocations from context of parasite. Therefore this is the only region that should be skipped.
> Drop CMD_GET_SKIP_ADDR

- memcr.c
Memcr service will send 'MEMCR_ERROR' in case of checkpointing an already checkpointed PID or trying to restore not checkpointed one.
> Send error response in case of wrong PID received

- memcr.c
PFN from pagemap is provided only when a page is present.
> Check if page is unevictable only for present pages

- memcr.c
When pthread_cond_timedwait() returns ETIMEDOUT the wait should continue.
> Retry parasite status wait after timeout

- Makefile
- memcr.c
Code and make dependencies related to compression are guarded by flags.
> Enable LZ4 compression for memory dumps.

- memcr-client.c
- memcr.c
- memcr.h
The status will be returned in case of checkpointing the already checkpointed application or restoring an application which is not checkpointed.
> MEMCR_INVALID_PID error code introduced.

- Makefile
- memcr.bb
- memcr.c
Both compression and checksumming rely on external libraries so these features are made optional at compile time. This is how you enable both of them:
$ make COMPRESS_LZ4=1 CHECKSUM_MD5=1
Once compiled in compression can be enabled with -z or --compress.
> Make compression and checksumming optional at compile time

- Makefile
- libencrypt.c
- memcr.bb
This is sample implementation of encryption layer for memcr based on libcrypto api. libencrypt.so can be built by adding ENCRYPT=1 to make arguments. memcr is not linked with libencrypt.so but it can be preloaded:
LD_PRELOAD=./libencrypt.so ./memcr ...
> Implement encryption layer in libencrypt.so

- memcr.c
All runtime options are available now but when support for underlying functionality is not compiled in memcr will exit with an error.
> Improve memcr options handling

- memcr.c
With this option you can connect to a parasite which is in a different network namespace from memcr, for example when the parasite is running in a container.
> Added option to use network namespace when connecting to parasite

- Makefile
- README.md
- arch/cpu.h
- arch/riscv64/cpu.c
- arch/riscv64/cpu.h
- arch/riscv64/enter.c
- arch/riscv64/linux-abi.h
- arch/riscv64/parasite-head.S
- arch/riscv64/parasite.lds.S
- arch/syscall.c
A new architecture RISCV64 has been added. Tested on SiFive VisionFive2
> Added suport for Riscv64 architecture

- memcr.c
Otherwise, If timeout is used and one of workers killed,  reading on another worker socket will fail with
__read() failed: Interrupted system call
> Continue read from sock on EINTR error

- Makefile
- memcr-client.c
- memcr.c
- memcr.h
git describe output should be good enough.
> Add memcr version info

- memcr.c
Make sure dump is removed, since the worker exit signal 
may come after the clean up of checkpoint data and can be not effective.
> Call PID clean up on checkpoint and restore timeout

- memcr.c
Do not cause crash when checkpointed PID with
parasite was externally terminated, and
parasite PID was already reaped by Memcr service process.
> Worker exit instead of crash on parasite not available
