memcr.c

There are two different variables named 'dir' in the source code. One of them is in global scope, the second one is local.

Source code 'dir' variables renamed to avoid confusion.

---

Makefile

To cross compile CC, LD and OBJCOPY are needed. Also CROSS_COMPILE handling is added. Linker needs to be of BFD type.

Improve cross compilation support

---

arch/arm/cpu.c
arch/arm/cpu.h
arch/cpu.h
arch/x86_64/cpu.c
arch/x86_64/cpu.h
memcr.c

This is a part of cleanup for arm64 port.

Provide struct registers per architecture

---

Makefile
arch/arm64/cpu.c
arch/arm64/cpu.h
arch/arm64/enter.c
arch/arm64/linux-abi.h
arch/arm64/parasite-head.S
arch/arm64/parasite.lds.S
arch/syscall.c
memcr.c

Tested on Raspberry Pi 4 Model B Rev 1.1 running Raspberry Pi OS (64-bit).

arm64: initial implementation

---

Makefile
memcr-client.c
memcr.bb
memcr.c
memcr.h

Simple localhost client added.

Memcr can listen on a TCP socket for requests.

---

memcr.c

Prepare the codebase to work in sevice mode in a loop and fork. Debug prints corrected in case of wrong command read.

Socket mode split from interactive mode to separate function.

---

memcr.c

Application will work in a loop in socket mode.
Retry command read in case of wrong parameters received.

Service mode for a single PID.

---

memcr.c

Changed checking if PID is already checkpointed.
PID to checkpoint is a local variable now.

Socket connection handling moved to a separate function.

---

memcr.c

Application will fork and handle every target PID in separate process. Internal communication between service and workers introduced. Worker exit status is ignored for now.

Memcr can handle multiple PIDs now.

---

memcr.c

Memcr worker will receive SIGCHLD in case of SIGKILL for tracee. Worker has to exit to allow the kill.
SIGPIPE will be generated and has to be handled in case of a client disappear during memcr procedure.

Signals handing in case of tracee is killed or client restart.

---

memcr.c

New sigset for rt_sigprocmask is stored on stack so it needs to be restored in case of a user signal delivery.

Save stack for execute_blob() retry

---

memcr.c

Passing by pointer is no longer needed as it was used for sigmask only and now sigmask is retrieved directly from stack.

Pass execute_blob() arg0 and arg1 by value

---

memcr.c

When a page is unevictable madvise() MADV_DONTNEED will fail. To handle that we can read page 64 bit mask from /proc/kpageflags and check if KPF_UNEVICTABLE bit is set. Also access() to /proc/self/pagemap and /proc/kpageflags is checked on memcr start. Presence of these files depends on kernel CONFIG_PROC_PAGE_MONITOR.

Handle unevictable pages

---

memcr.c

Delete not needed dumps and sockets:
- on memcr exit
- on memcr worker or app SIGKILL
- on checkpoint failure
- on restore
And terminate checkpointed processes on memcr exit

Cleanup of Dump and Work dir on exit or error

---

memcr.c

This change allows additional logic of dump file handling to be provided by external library (i.e. encryption).
Some of vm region code was rewritten to make it more readable.
Option -e or --encrypt is now passed to the lib__init().

Support for external handling of dump file io

---

.github/workflows/ci-arm.yml
.github/workflows/ci-arm64.yml
.github/workflows/ci-clang.yml
.github/workflows/ci-riscv64.yml
.github/workflows/ci-x86_64.yml

actions/checkout v3 is deprecated.

Update CI actions/checkout to v4

---

memcr.c

Optional timeout to prevent service thread to be blocked by unresponsive worker process

Support cmd execution timeout in service mode

---

memcr.c

If more than one service child is killed,
the SIGCHLD signals can be coalesced, causing service to miss worker exit and perform clean-up

sigchld_handler_service: Iterate over all service children

---

Makefile
tests/Makefile
tests/run.sh
tests/test-malloc.c

This should make testing across multiple platforms easier.

Implement initial test framework

---

memcr.c

Also fail when encryption is requested but libencrypt.so is not preloaded.

Improve messages when some of options are not available

---

Makefile
memcr.c

This should make anlyzing logs easier.

Print memcr arch and kernel uname info
